# Site settings
title: Code Gardener
# header-img: img/home-bg.jpg
email: miguelerm@gmail.com
copyright_name: CodeGardener.Net
description: "Un microblog para hablar de microservices"
baseurl: ""
url: "http://www.codegardener.net"

author:
  name     : 'Miguel Román'
  email    : miguelerm@gmail.com
  url      : https://plus.google.com/+MiguelEduardoRomanMartinez/about
  facebook : miguelerm
  twitter  : miguelerm
  github   : miguelerm

disqus_shortname: "codegardener"
google_analytics: UA-40921433-2

excerpt_separator: <!-- more -->

compress_html:
  comments: ["<!-- ", " -->"]

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules","Gruntfile.js","package.json","README.md"]
  
gems: [jekyll-paginate, jekyll-feed]
